# Generated by Django 4.2.8 on 2023-12-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productscategory',
            options={'verbose_name_plural': 'Products Categories'},
        ),
    ]
